require "./lib/Snippet"
require "./lib/Experiments"
require "Bio"
require 'ruby-debug' ; Debugger.start(:post_mortem => true)


puts "** nmPgll truncation primers **"

nMtemplate = "atgcccgctgaaacgaccgtatccggcgcgcaccccgccgccaaactgccgatttacatc
ctgccctgcttcctttggataggcatcgtcccctttaccttcgcgctcaaactgaaaccg
tcgcccgacttttaccacgatgccgccgccgcagccggcctgattgtcctgttgttcctc
acggcaggaaaaaaactgtttgatgtcaaaatccccgccatcagcttccttctgtttgca
atggcggcgttttggtatcttcaggcacgcctgatgaacctgatttaccccggtatgaac
gacatcgtctcttggattttcatcttgctcgccgtcagcgcgtgggcctgccggagcttg
gtcgcacacttcggacaagaacgcatcgtgaccctgtttgcctggtcgctgcttatcggc
tccctgcttcaatcctgcatcgtcgtcatccagtttgccggctgggaagacacccctctg
tttcaaaacatcatcgtttacagcgggcaaggcgtaatcggacacatcgggcagcgcaac
aacctcggacactacctcatgtggggcatactcgccgccgcctacctcaacggacaacga
aaaatccccgccgccctcggcgtaatctgcctgattatgcagaccgccgttttaggtttg
gtcaactcgcgcaccatcttgacctacatagccgccatcgccctcatccttcccttctgg
tatttccgttcggacaaatccaacaggcggacgatgctcggcatagccgcagccgtattc
cttaccgcgctgttccaattttccatgaacaccattctggaaacctttactggcatccgc
tacgaaactgccgtcgaacgcgtcgccaacggcggtttcacagacttgccgcgccaaatc
gaatggaataaagcccttgccgccttccagtccgccccgatattcgggcacggctggaac
agttttgcccaacaaaccttcctcatcaatgccgaacagcacaacatatacgacaacctc
ctcagcaacttgttcacccattcccacaacatcgtcctccaactccttgcagagatggga
atcagcggcacgcttctggttgccgcaaccctgctgacgggcattgccgggctgcttaaa
cgccccctgacccccgcatcgcttttcctaatctgcacgcttgccgtcagtatgtgccac
agtatgctcgaatatcctttgtggtatgtctatttcctcatccctttcggactgatgctc
ttcctgtcccccgcagaggcttcagacggcatcgccttcaaaaaagccgccaatctcggc
atactgaccgcctccgccgccatattcgcaggattgctgcacttggactggacatacacc
cggctggttaacgccttttcccccgccactgacgacagtgccaaaaccctcaaccggaaa
atcaacgagttgcgctatatttccgcaaacagtccgatgctgtccttttatgccgacttc
tccctcgtaaacttcgccctgccggaataccccgaaacccagacttgggcggaagaagca
accctcaaatcactaaaataccgcccccactccgccacctaccgcatcgccctctacctg
atgcggcaaggcaaagttgcagaagcaaaacaatggatgcgggcgacacagtcctattac
ccctacctgatgccccgatacgccgacgaaatccgcaaactgcccgtatgggcgccgctg
ctacccgaactgctcaaagactgcaaagccttcgccgccgcgcccggtcatccggaagca
aaaccctgcaaagaaaacctgtattttcagggccaccaccaccaccaccaccaccaccac
cactga"


nMtruncations_to_make = ["vnafs-enlyfqg",
 "elryi-enlyfqg", "slvnf-enlyfqg", "tlksl-enlyfqg", "lylmr-enlyfqg", "atqsy-enlyfqg", "deirk-enlyfqg", "kafaa-enlyfqg", "vsgahp-vkipai"]

nMtruncations_to_make.each do |x|
	puts x
	obj = DeletionExperiment.new(x, nMtemplate)
	obj.printData
	puts "======"
end

# vctemplate = "atgaactgcatggcaactttgctgttaagtggcactcggttggaacctcacgctccgaac
# ctaccactcaataaaccgtttctttttgccttggccgtggtttatctgctcgccatgcat
# ttctttatgcctaaccccggcggtgctggactggcactctccttcaatactacggtctgg
# atcgcgaccagcataacactggcgattggtctgtatcagttggcgaataatcaagcgctg
# cgttattccaagctgaccattggactttggttaagctgtgctctgctaaccctacccatc
# acttactcgaatgccgattggtttcatactcttggccgcttagtgggtctctgggctgga
# tttactctgtttctcgtcttacaacaatttcgctttagcaacaaacataaacagcgtttg
# ctgtggtttattctactgggtagcgtcattgaagccgtgatcggtttaattcaatacttt
# tggttagagccgggtaacccctttggttatgacaccgaagcaaatcgaccgtatggtatt
# ttccagcaaccaaatgtgatggccagtttcctcgcaacagggctggtgttgtcaggttat
# ttgctggccagacaaccggaaaaatatgactcgcgctggagcaaaatcggcatcctttac
# gcgacaccgctactcacggctcccttactggtcgtactcgcctctcgcactgggtggctg
# gccagtttattgagtatcgctctggttgccccttacttatatcgattcgcttcacgtcgg
# cgctttacgctctggcttcttgccataactcttgggatttgtgcaggttttaccgctatg
# tatggccaaggaacctctggttttgtcgcgaataaggctgacttagaaagcccacgtcgt
# ttcacatttccacaaaccatagatatgatcatcgaaaagccttttacaggctatggttat
# ggcaaatttgaggcgcagtatctgctttatactgctcgccaacatcagttaaatagcagc
# tatccagcaggcttagcatcgatggatcacccacacaatgagctgttgtattggggggta
# gaaggcggattactacctgtaatgggtatattactcgccgcctgtttttgtgctctacgc
# atttatgccgccaaacgtggcactcgcatggccatgctggctctgtttgtgccgatcacc
# ttacacgctcaattggagtatccgttttaccactccgcaattcactggatcacctttatc
# atcctaatctactgggtagatcaacgggtcgcacgctatcgactggccagtttcaccacg
# ctcaccaaatctttattgcgtattaccagcttagtgctgccgattgtcaccagcttgtat
# atggtcacagcgttacacaccaactatgtgttaacgcaatttgaaaaatctcagccactc
# aatcctgaattgctgaaaaacgtgactaacccattggtatggcaagaccgatttgattgg
# gatatctacagcacctatctgaacatcgggctccatgaacaaaaagcggagcttatccaa
# ccctatatcgattggtcgttacagatcattcaacataaaccgcgcccggccttctattca
# aacctgattttggcttatcaaggtttaggcgatacgagccgtgcgcagcaaatccgccgc
# gaggccgaatttctgttccccaatcaagatttcagtacagtccagtaccacccctcgata
# aaggtcaacagtgccacatctgatgctgaggttccctcagccgcgacaccccaccaccaccaccaccactaaaagcttggctgttttggcggatgagaga"

# vCtruncations_to_make = ["TQFE-HHHHHH",
# 						 "LNIGL-HHHHHH",
# 						 "LQII-HHHHHH",
# 						 "AYQG-HHHHHH",
# 						 "AEFL-HHHHHH",
# 						 "SIKV-HHHHHH"]

# vCtruncations_to_make.each do |x|
# 	obj = DeletionExperiment.new(x, vctemplate)
# 	obj.printData
# 	puts "======"
# end

