require "./Snippet"
require "./Experiments"
require "test/unit"
require "Bio"
require "amatch"


@template = "atgcccgctgaaacgaccgtatccggcgcgcaccccgccgccaaactgccgatttacatc
		ctgccctgcttcctttggataggcatcgtcccctttaccttcgcgctcaaactgaaaccg
		tcgcccgacttttaccacgatgccgccgccgcagccggcctgattgtcctgttgttcctc
		acggcaggaaaaaaactgtttgatgtcaaaatccccgccatcagcttccttctgtttgca
		atggcggcgttttggtatcttcaggcacgcctgatgaacctgatttaccccggtatgaac
		gacatcgtctcttggattttcatcttgctcgccgtcagcgcgtgggcctgccggagcttg
		gtcgcacacttcggacaagaacgcatcgtgaccctgtttgcctggtcgctgcttatcggc
		tccctgcttcaatcctgcatcgtcgtcatccagtttgccggctgggaagacacccctctg
		tttcaaaacatcatcgtttacagcgggcaaggcgtaatcggacacatcgggcagcgcaac
		aacctcggacactacctcatgtggggcatactcgccgccgcctacctcaacggacaacga
		aaaatccccgccgccctcggcgtaatctgcctgattatgcagaccgccgttttaggtttg
		gtcaactcgcgcaccatcttgacctacatagccgccatcgccctcatccttcccttctgg
		tatttccgttcggacaaatccaacaggcggacgatgctcggcatagccgcagccgtattc
		cttaccgcgctgttccaattttccatgaacaccattctggaaacctttactggcatccgc
		tacgaaactgccgtcgaacgcgtcgccaacggcggtttcacagacttgccgcgccaaatc
		gaatggaataaagcccttgccgccttccagtccgccccgatattcgggcacggctggaac
		agttttgcccaacaaaccttcctcatcaatgccgaacagcacaacatatacgacaacctc
		ctcagcaacttgttcacccattcccacaacatcgtcctccaactccttgcagagatggga
		atcagcggcacgcttctggttgccgcaaccctgctgacgggcattgccgggctgcttaaa
		cgccccctgacccccgcatcgcttttcctaatctgcacgcttgccgtcagtatgtgccac
		agtatgctcgaatatcctttgtggtatgtctatttcctcatccctttcggactgatgctc
		ttcctgtcccccgcagaggcttcagacggcatcgccttcaaaaaagccgccaatctcggc
		atactgaccgcctccgccgccatattcgcaggattgctgcacttggactggacatacacc
		cggctggttaacgccttttcccccgccactgacgacagtgccaaaaccctcaaccggaaa
		atcaacgagttgcgctatatttccgcaaacagtccgatgctgtccttttatgccgacttc
		tccctcgtaaacttcgccctgccggaataccccgaaacccagacttgggcggaagaagca
		accctcaaatcactaaaataccgcccccactccgccacctaccgcatcgccctctacctg
		atgcggcaaggcaaagttgcagaagcaaaacaatggatgcgggcgacacagtcctattac
		ccctacctgatgccccgatacgccgacgaaatccgcaaactgcccgtatgggcgccgctg
		ctacccgaactgctcaaagactgcaaagccttcgccgccgcgcccggtcatccggaagca
		aaaccctgcaaatga".strip.delete("\n\t")

		@aaSeq = 'MPAETTVSGAHPAAKLPIYILPCFLWIGIVPFTFALKLKPSPDFYHDAAAAAGLIVLLFL
		TAGKKLFDVKIPAISFLLFAMAAFWYLQARLMNLIYPGMNDIVSWIFILLAVSAWACRSL
		VAHFGQERIVTLFAWSLLIGSLLQSCIVVIQFAGWEDTPLFQNIIVYSGQGVIGHIGQRN
		NLGHYLMWGILAAAYLNGQRKIPAALGVICLIMQTAVLGLVNSRTILTYIAAIALILPFW
		YFRSDKSNRRTMLGIAAAVFLTALFQFSMNTILETFTGIRYETAVERVANGGFTDLPRQI
		EWNKALAAFQSAPIFGHGWNSFAQQTFLINAEQHNIYDNLLSNLFTHSHNIVLQLLAEMG
		ISGTLLVAATLLTGIAGLLKRPLTPASLFLICTLAVSMCHSMLEYPLWYVYFLIPFGLML
		FLSPAEASDGIAFKKAANLGILTASAAIFAGLLHLDWTYTRLVNAFSPATDDSAKTLNRK
		INELRYISANSPMLSFYADFSLVNFALPEYPETQTWAEEATLKSLKYRPHSATYRIALYL
		MRQGKVAEAKQWMRATQSYYPYLMPRYADEIRKLPVWAPLLPELLKDCKAFAAAPGHPEA
		KPCK-'

@expString = 'LGVI*A*LIMQ'

@exp = SubstitutionExperiment.new(@expString, @template)

